package com.Clases;

public enum EnumComunaBucaramanga {
    NORTE, NORORIENTAL, SAN_FRANCISCO, OCCIDENTAL, GARCIA_ROVIRA, CONCORDIA, CIUDADELA, SUROCCIDENTE, PEDREGOSA, PROVENZA, SUR, CABECERA, ORIENTAL, MORRORRICO, CENTRO, LAGOS, MUTIS
}
