package com.Clases;

public enum EnumComunaGiron {
    CASCO_URBANO, ACAPULCO, BARBOSA, BOCAS, CANTALTA, CARRIZAL, CHOCOA, CHOCOITA, CEDRO, PARROQUIA, LAGUNETAS, LLANADAS,
    LLANO_GRANDE, MARTHA, MOTOSO, PATO_GORDO, PANTANO, PENAS, RIO_FRIO, SOGAMOSO
}
